repos:
  - repo: meta
    hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.25
    hooks:
    - id: actionlint
