on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      envlist:
        required: false
        type: string
        default: '["py38", "py39", "py310", "py311"]'
      arch:
        required: false
        type: string
        default: '["x64"]'

jobs:
  tox:
    name: tox on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.envlist) }}
        arch: ${{ fromJSON(inputs.arch) }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: |
          ${{
            matrix.env == 'py38'  && '3.8'  ||
            matrix.env == 'py39'  && '3.9'  ||
            matrix.env == 'py310' && '3.10' ||
            matrix.env == 'py311' && '3.11' ||
                                     '3.12'
          }}
        architecture: ${{ matrix.arch }}
    - run: python -m pip install --upgrade pip
    - run: python -m pip install tox flit
    - name: Lint
      run: tox -e pre-commit
    - name: Test
      run: tox -e ${{ matrix.env }}
