on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: '["ubuntu-latest"]'
      arch:
        required: false
        type: string
        default: '["x64"]'
      env:
        required: false
        type: string
        default: '["py38", "py39", "py310", "py311", "py312", "pre-commit"]'

jobs:
  tox:
    name: ${{ matrix.os }}/${{ matrix.env }}/${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os) }}
        arch: ${{ fromJSON(inputs.arch) }}
        env: ${{ fromJSON(inputs.env) }}
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # v4.1.0
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # v5.1.0
      with:
        python-version: |
          ${{
            matrix.env == 'py38'  && '3.8'  ||
            matrix.env == 'py39'  && '3.9'  ||
            matrix.env == 'py310' && '3.10' ||
            matrix.env == 'py311' && '3.11' ||
                                     '3.12'
          }}
        architecture: ${{ matrix.arch }}
    - run: python -m pip install --upgrade pip
    - run: python -m pip install tox
    - name: Test
      run: tox -e ${{ matrix.env }}
