on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      envlist:
        required: false
        type: string
        default: '["py38", "py39", "py310", "py311", "py312", "pre-commit"]'
      arch:
        required: false
        type: string
        default: '["x64"]'

jobs:
  tox:
    name: ${{ inputs.os }}/${{ matrix.env }}/${{ matrix.arch }}
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.envlist) }}
        arch: ${{ fromJSON(inputs.arch) }}
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # v4.1.0
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236  # v4.7.1
      with:
        python-version: |
          ${{
            matrix.env == 'py38'  && '3.8'  ||
            matrix.env == 'py39'  && '3.9'  ||
            matrix.env == 'py310' && '3.10' ||
            matrix.env == 'py311' && '3.11' ||
                                     '3.12'
          }}
        architecture: ${{ matrix.arch }}
    - run: python -m pip install --upgrade pip
    - run: python -m pip install tox
    - name: Test
      run: tox -e ${{ matrix.env }}
